// try{

    
// }
// catch(err){

//     console.log(err.message)
// }
// var num=10;
//     var da=num.toUpperCase()
//     console.log(da)

// var data=10;

// console.log(data.toUpperCase());

// console.log("transction")


//ecxception is an abnormal condtion that disrupt normal flow of our program


// we can handle the exception by using exception handlin mechanisam try catch 


// try{

//     // doubtfulcode
// }
// catch(){

//   //  handling code
// }



// try{


//     var data=10;
//     console.log(data.toUpperCase());
// }
// catch(err){

//     console.log(err.message)
// }
try{
    var age=18;
    if(age<19) throw "invalid age";
}
catch(err){
    console.log(err)
}




